Repository flox/floxdocs, pull requests merged in 2025-01, with the labels that each got.

#115 docs(nvm.md): Improve utility of Flox command snippets
  docs/tutorials/migrations/nvm.md
Labels: documentation

#117 chore: Release 1.3.9
  FLOX_VERSION
  docs/tutorials/migrations/nvm.md
  poetry.lock
Labels: documentation

#111 Adding suggestion for -d with $HOME folder
  docs/tutorials/default-environment.md
Labels: documentation, Community ❤️

#112 Added tip to use `flox envs`
  docs/tutorials/layering-multiple-environments.md
Labels: Community ❤️

#118 chore: Release 1.3.10
  FLOX_VERSION
Labels: documentation

#120 fix: clarify the runtime-packages build option
  docs/concepts/manifest-builds.md
Labels: documentation

#122 chore: Release 1.3.11
  FLOX_VERSION
Labels: documentation

#124 Fix linting
  .flox/env/manifest.lock
  .flox/env/manifest.toml
  .github/workflows/ci.yml
  .markdownlint-cli2.yaml
  docs/tutorials/migrations/homebrew.md
  docs/tutorials/migrations/nvm.md
Labels: documentation
